### ISSUE TITLE
Flutter SDK

### ISSUE THREAD

**Issue by svareniem** [crowdin/mobile-sdk-android#101]
I love your OTA and Real-time updates feature for Android/iOS. Would be great to have Crowdin SDK for Flutter.
Thanks for the great work!

**Comment by andrii-bodnar** [comment]
We are excited to announce the beta release of **Crowdin Flutter SDK**! 🎉 

Visit the [crowdin/flutter-sdk](https://github.com/crowdin/flutter-sdk) repository for more details.

Feedback is extremely valuable to us, don't hesitate to leave comments in the related discussion - https://github.com/crowdin/flutter-sdk/discussions/10
