### ISSUE TITLE
TextView marquee is not working

### ISSUE THREAD

**Issue by naiyu** [crowdin/mobile-sdk-android#139]
After using the Crowdin Android sdk for a few month, I found a bug that a textview can't marquee correctly while set a long text to it in  java code or koltin code, just like that 
```kolin
myTextView.text = "123456789987654321123456789987654321"
```
And It can be marquee correctly while init in xml:

```xml
<TextView
        android:id="@+id/tv_marquee"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="@string/long_str"
        android:textColor="#333333"
        android:singleLine="true"
        android:ellipsize="marquee"
        android:marqueeRepeatLimit="marquee_forever"
        android:scrollHorizontally="true"
        android:focusable="true"
        android:focusableInTouchMode="true"
        android:freezesText="true"
        android:textSize="22sp"/>
```
the long_str is

```xml
<string name="long_str">123456789987654321123456789987654321</string>
```

**Comment by andrii-bodnar** [comment]
Hi @naiyu! Could you please provide more details about this bug? 

- What is the actual behavior and expected behavior
- Screenshots if possible
- Device and OS versions

**Comment by naiyu** [comment]
@andrii-bodnar 
after update the text by a kotlin code
```kotlin
myTextView.text = "123456789987654321123456789987654321"
```
it becomes: 
![haomab0c](https://user-images.githubusercontent.com/19882884/125252870-6e62ce00-e32b-11eb-95f9-27f0edd3dca4.jpg)

I need it do the marquee effect

os version: Android 10.

**Comment by andrii-bodnar** [comment]
@naiyu did you tried to use setter?

```kotlin
val textId = typedArray.getResourceId(R.styleable.sample_item, 0)
textView.setText(textId)
```

**Comment by naiyu** [comment]
@

> @naiyu did you tried to use setter?
> 
> ```kotlin
> val textId = typedArray.getResourceId(R.styleable.sample_item, 0)
> textView.setText(textId)
> ```

The new content string is from api, not in a strings.xml

**Comment by naiyu** [comment]
I write a demo [here](https://github.com/naiyu/MyCrowdinDemo). Maybe it can help your reproduce this bug. @andrii-bodnar

**Comment by andrii-bodnar** [comment]
@naiyu thanks a lot for the details provided!
