### ISSUE TITLE
HTML select tag crash on WebView

### ISSUE THREAD

**Issue by walterjuanp** [crowdin/mobile-sdk-android#148]
**Describe the bug**
Clicking on a website that contains a select, the app crash instead of showing the select options.

**To Reproduce**
Sample project has been created: https://github.com/walterjuanp/crowdin_sdk_webview_crash

**Expected behaviour**
It should be the default behaviour on Android, showing a dialog with all options from the select

**Smartphone (please complete the following information):**
 - Emulator, Pixel 4 API 29

**Comment by Natalia936** [comment]
Hi @walterjuanp !
Thank you for pointing that, our devs will check it
