### ISSUE TITLE
exported field error when targeting Android >=12

### ISSUE THREAD

**Issue by MysteryMS** [crowdin/mobile-sdk-android#191]
**Describe the bug**
The `exported` field is missing in the manifest, which is required when targeting Android 12, throwing the following error:
`android:exported needs to be explicitly specified for element <activity#com.crowdin.platform.auth.AuthActivity>`

**To Reproduce**
1. Create a Jetpack Compose Android project that targets API 33
2. Set up the Android SDK integration
4. Build and see error

**Expected behavior**
The crash shouldn't happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/38635037/211122086-f17643b9-2c81-4cd8-a54a-6c1ca1e1bf74.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 6 (emulator)
 - OS: Android 12

**Comment by Andrulko** [comment]
Thank you very much for pointing that out! Engineers will look into it shortly

**Comment by MysteryMS** [comment]
Just saw the label. #192 should fix this issue.

**Comment by MysteryMS** [comment]
Sorry for the confusion. For some reason Android Studio didn't warn about a newer version, was running on 1.4.1.
