### ISSUE TITLE
HTML select tag crash on WebView

### ISSUE THREAD

**Issue by walter-juan** [crowdin/mobile-sdk-android#194]
**Describe the bug**
Clicking on a website that contains a select, the app crash instead of showing the select options.

**To Reproduce**
A sample project has been created: https://github.com/walter-juan/crowdin_sdk_webview_crash

**Expected behavior**
It should be the default behavior on Android, showing a dialog with all options from the select

**Screenshots**
Crash
https://user-images.githubusercontent.com/4141614/225893490-299c884c-b6f6-4680-91d7-fac9bae4d72b.mp4
Expected behavior (using Google Chrome)
https://user-images.githubusercontent.com/4141614/225893403-7f198b15-b13d-46c0-811d-ef34ad9a4035.mp4

**Smartphone (please complete the following information):**
 - Samsung Galaxy A53 5G, Android 13
 - Emulator, Pixel 4 API 29

**Additional context**
Bug already reported some time ago ([HERE the Issue](https://github.com/crowdin/mobile-sdk-android/issues/148)) and closed because it was not possible to reproduce

**Comment by walter-juan** [comment]
Nope, no idea =(

**Comment by RasM24** [comment]
Hello! Try to create WebView programmatically using applicationContext:

```
webView = WebView(requireContext().applicationContext)
  .apply { layoutParams = LayoutParams(MATCH_PARENT, MATCH_PARENT) }

fragment_layout.addView(webView)
```

---------------------

override `Resources` not supported by google: https://issuetracker.google.com/issues/77246450#comment4
WebView have many bugs, for sample:
https://issuetracker.google.com/issues/162779750
https://issuetracker.google.com/issues/140652425

also WebView can't work correctly with non-standard resources. I lost the issue but i can replicate the error by using `ContextWrapper` with `override getResources()`

Summary - use ChromeTab :)
