### ISSUE TITLE
AppCompatDelegate.setApplicationLocales not working due to crowdin need of overriding getDelegate in activities

### ISSUE THREAD

**Issue by jablkojem** [crowdin/mobile-sdk-android#200]
**Describe the bug**
I need to implement in app language switch. Based on android documentation https://developer.android.com/guide/topics/resources/app-languages#androidx-impl - this is recommended to use. I am already using crowdin over the air and based on example app, I need to do this in all activities : 
`override fun getDelegate(): AppCompatDelegate = BaseContextWrappingDelegate(super.getDelegate())`
- if I remove this getDelegate() override, setApplicationLocales() method is changing app language as expected
I need to make it work together somehow.

**To Reproduce**
1. Try to change app language via AppCompatDelegate.setApplicationLocales in your example app https://github.com/crowdin/mobile-sdk-android/tree/master/example
2. language is not changed
3. try to remove getDelegateOverride
4. language is changed

**Expected behavior**
I think I should be able to change app language via AppCompatDelegate.setApplicationLocales and also use crowdin sdk for over-the-air translations.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 13

**Comment by evgenygorovoy** [comment]
hey, any news about this bug?
