### ISSUE TITLE
Crowdin over-the-air not working with default variant of spanish language

### ISSUE THREAD

**Issue by jablkojem** [crowdin/mobile-sdk-android#204]
**Describe the bug**
We are using crowdin over-the-air for real time text changes in our app. We are using **default** spanish language and over the air translations are not working. If we try to set for example "Spanish, Costa rica" variant of spanish language and we have this language also set in android system settings, everything works. If we try the same with default Spanish language, translations are not downloaded & updated. 

**To Reproduce**
1. Create over-the-air content delivery and add spanish language to crowdin (default spanish + for example costa rica variant of spanish language)
2. Set default spanish as system language in android system settings
3. Try over-the-air content delivery -> not working
4. Set "Spanish, Costa rica" (or any other spanish variant) as system language in android system settings
5. Try over-the-air content delivery -> working

**Expected behavior**
If default spanish language is set in android system settings, and this language is also in crowdin - I would expect it to be working. If I try some other variant of spanish language, or any other language (for example Slovenian), it works.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 13

**Comment by andrii-bodnar** [comment]
Hi @jablkojem, we have not been able to reproduce this case. Could you please provide a minimal reproducible example? Thank you very much!

**Comment by jablkojem** [comment]
Hi @andrii-bodnar ,
I have prepared demo app - https://github.com/jablkojem/EsDemoApp 
I have created new crowdin project - https://crowdin.com/project/esdemoapp

Demo app contains just one textview which should be updated OTA, newly created crowdin project has this language setup :
![image](https://github.com/crowdin/mobile-sdk-android/assets/26108416/366e2ff6-c50e-4869-9353-fc076aac3ce1)

On my phone, I am testing with these 2 languages :
![image](https://github.com/crowdin/mobile-sdk-android/assets/26108416/4373a71a-b859-46ef-a7d2-19948d93948a)

As I tested with this new crowdin project, both languages worked....so I tried with origin project (**which is on enterprise crowdin**) and there default spanish doesnt work (only es-CR works here).
In demo app, if you replace basicProjectHash with enterpriseProjectHash when initializing crowdin (class com.msoft.crowdindemoapp.app.App) you can demonstrate the behavior. 
basicProjectHash is hash of the newly created project where both languages work, enterpriseProjectHash is hash of my enterprise project where default ES language doesnt work. Setup of languages is the same in crowdin for both projects and I am testing with the same languages also on my device. 
So problem is that for enterprise project, "Spanish, Costa Rica" works but default spanish isnt.

Here is language setup for enterprise project :
![image](https://github.com/crowdin/mobile-sdk-android/assets/26108416/537fc2c1-66d5-4d1b-8395-92b17a4d9eb6)

So based on this, basic crowdin project works also with default variant of spanish language, but enterprise project doesnt work the same way.

**Comment by andrii-bodnar** [comment]
Available in [1.8.0](https://github.com/crowdin/mobile-sdk-android/releases/tag/1.8.0)
