### ISSUE TITLE
Attributes from the theme of the parent view are lost to the view from SupportedCustomViews.

### ISSUE THREAD

**Issue by Object173** [crowdin/mobile-sdk-android#206]
**Describe the bug**

After adding the `BaseContextWrappingDelegate` to inflate from the MaterialAutoCompleteTextView xml, it is not the context from Activity that is used (the style set in the parent view theme is lost).

**To Reproduce**

BaseActivity
```
override fun getDelegate() = BaseContextWrappingDelegate(super.getDelegate())
```
style.xml
```
<style name="ThemeOverlay.AutoCompleteTextView" parent="">
    <item name="autoCompleteTextViewStyle">@style/AutoCompleteTextView</item>
</style>

<style name="AutoCompleteTextView" parent="Widget.MaterialComponents.AutoCompleteTextView.FilledBox.Dense">
    <item name="android:background">@color/black</item>
</style>
```
layout.xml
```
<com.google.android.material.textfield.TextInputLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:materialThemeOverlay="@style/ThemeOverlay.AutoCompleteTextView">

<com.google.android.material.textfield.MaterialAutoCompleteTextView
    android:layout_width="match_parent"
    android:layout_height="wrap_content"/>

</com.google.android.material.textfield.TextInputLayout>
```

**Expected behavior**

`MaterialAutoCompleteTextView` uses the `AutoCompleteTextView` style from the parent view's theme.

**Additional context**

The problem lies with the `CrowdinLayoutInflater`. supportedCustomViews contains the string "TextView" without a package, so any view containing "TextView" in the name (and hence `MaterialAutoCompleteTextView`) falls under the `supportedCustomViews` rules. 
```
private val supportedCustomViews = listOf(
        "com.google.android.material.bottomnavigation.BottomNavigationView",
        "com.google.android.material.navigation.NavigationView",
        "com.google.android.material.button.MaterialButton",
        "androidx.appcompat.widget.AppCompatButton",
        "TextView"
)
```
Such views are created through the `LayoutInflater.createView(String, String, AttributeSet)` function, which is not passed the context from `Factory2`, so the `LayoutInflater` uses the base context instead of the context of the parent view.

<img width="653" alt="Screenshot 2023-07-27 at 22 15 52" src="https://github.com/crowdin/mobile-sdk-android/assets/26117240/f6c25c89-1c9a-465b-9784-5ece487d4f73">
<img width="759" alt="Screenshot 2023-07-27 at 22 09 48" src="https://github.com/crowdin/mobile-sdk-android/assets/26117240/5f75ba1f-3ee0-484a-8c8e-a0f72e984ab0">

The following points raise questions:
1. Many views can contain the string "TextView", isn't this a too general rule and is it necessary to add a package?
2. Why is the context passed to `Factory2` ignored? Is losing the theme of the parent view the expected behavior?

**Version**

SDK 1.5.9

**Comment by Object173** [comment]
After [revert](https://github.com/crowdin/mobile-sdk-android/pull/211) the problem is again relevant

**Comment by andrii-bodnar** [comment]
Unfortunately, it's not possible with the current Android SDK version. We can't pass the context to the `createView` in this case.

It seems like the `MaterialAutoCompleteTextView` component only works incorrectly with the parent theme. You can replace this component with the `AutoCompleteTextView` if possible, it should work well.

**Comment by Object173** [comment]
I think that such a side effect needs to be reflected in the documentation because it is not obvious behavior. Overriding styles for views through a Theme or ThemeOverlay is a legal Android mechanism and the loss of the parent context can lead to serious and not obvious problems after integrating Crowdin SDK.
