### ISSUE TITLE
minSdkVersion 29 too high

### ISSUE THREAD

**Issue by Object173** [crowdin/mobile-sdk-android#210]
In SDK version 1.6.0 minSdkVersion was raised which makes it impossible to use it in our project (and many others). The 16 -> 29 step is too big. API 29 only covers 72.2% of android users (according to google statistics) which is too low for production apps. 

Might need to be revisited solving the problem of using Context in LayoutInflator to avoid using the new API. https://github.com/crowdin/mobile-sdk-android/pull/207

<img width="550" alt="Screenshot 2023-08-09 at 14 20 04" src="https://github.com/crowdin/mobile-sdk-android/assets/26117240/a13e71bc-e8e6-40ed-9de2-88246f0a0c90">

**Comment by isles1217** [comment]
+1 here. Honestly this seems like this was done in error? This is a huge oversight, especially for a localization library.
