### ISSUE TITLE
Over the air content delivery not working for Preference & PreferenceCategory views

### ISSUE THREAD

**Issue by jablkojem** [crowdin/mobile-sdk-android#213]
**Describe the bug**
Over the air content delivery is not working with preferences & preference categories. Strings are not updated - defaults are used instead.

**To Reproduce**
Try to add this view to your layout 
`    <PreferenceCategory
        android:layout="@layout/layout_preference_category"
        android:summary="@string/second"
        android:title="@string/first">`

**Expected behavior**
If string 'first' or 'second' is changed in crowdin and translations are released, I would expect these strings to be changed in the app. If I use these strings in standard TextView, it works. If I use Preference or PreferenceCategory view, it doesnt.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 13

**Comment by MykhailoNester** [comment]
Hello @jablkojem,

Thank you for submitting your issue. Unfortunately, the current version of our SDK does not support the direct definition of string resources in XML preferences.

For more details on limitations, please refer to our documentation: [SDK Setup Limitations](https://crowdin.github.io/mobile-sdk-android/setup#limitations).

As a workaround, you can dynamically set string resources in your code. Below is an example of how you can achieve this:

```
class PreferencesFragment : PreferenceFragmentCompat() {
    override fun onCreatePreferences(savedInstanceState: Bundle?, rootKey: String?) {
        setPreferencesFromResource(R.xml.preferences, rootKey)

        findPreference<SwitchPreferenceCompat>("notifications")?.title = getString(R.string.notification_title)
        findPreference<Preference>("feedback")?.title = getString(R.string.feedback_title)
    }
}
```
In this snippet, we dynamically set the titles for the "notifications" and "feedback" preferences using getString(R.string.your_string_resource). 

I hope this solution will be helpful for your implementation. If you have further questions or need additional assistance, please feel free to reach out.
