### ISSUE TITLE
Where can I get  distribution_hash?

### ISSUE THREAD

**Issue by breakadmin** [crowdin/mobile-sdk-android#226]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3]
 - OS: [e.g. Android X]

**Additional context**

**Comment by andrii-bodnar** [comment]
- [Setup](https://crowdin.github.io/mobile-sdk-android/setup)
- [Creating a distribution](https://support.crowdin.com/content-delivery/)
