### ISSUE TITLE
Crowdin Over The Air - third party dependency

### ISSUE THREAD

**Issue by mlefrapper** [crowdin/mobile-sdk-android#253]
Hello, I have implemented Crowdin Over The Air following the instructions in the documentation. It works correctly for screens from my application.
When I integrate a screen from a third-party dependency and I want to update the translation through Crowdin Over The Air, it doesn't work.
I can't apply the changes to the BaseActivity because it's not my application's code.

I've tried to do this via a registerActivityLifecycleCallbacks() but it doesn't work.

How should I handle this?

**Comment by andrii-bodnar** [comment]
Hi @mlefrapper, I guess it's something the SDK doesn't have access to. The 3rd party dependency should support i18n itself.
