### ISSUE TITLE
Would you consider adding a Xamarin SDK?

### ISSUE THREAD

**Issue by silverl** [crowdin/mobile-sdk-android#39]
Are there any plans to offer a Xamarin-based SDK?

Thank you.

**Comment by crowdin-support** [comment]
Hi Larry,

We'll check that with the developers and get back to you with the updates in the short term.

Let's stay tuned

**Comment by silverl** [comment]
Hello. Any update on the Xamarin SDK? Thank you.

**Comment by OlenaKot** [comment]
Hello Larry! 
Sorry for the late reply! Thank you so much for the request, it is on our roadmap, but it'll take a bit more time and currently, there is no ETA for this. As soon as we will have any updates regarding Xamarin SDK, you'll be the first person we contact
Wishing you a lovely day and let's keep in touch

**Comment by andrii-bodnar** [comment]
Hi @silverl!

Finally, we made it - [xamarin-sdk](https://github.com/crowdin/xamarin-sdk) :tada:

Feel free to try this SDK. We would be happy to have some feedback! Please note that SDK is in beta for now.

**Comment by silverl** [comment]
Thanks for the update, @andrii-bodnar, great to hear!

Our application pre-dates Xamarin.Forms. We only use Xamarin, without the Forms. Our long term plan is to move to .NET MAUI, the successor to Xamarin.Forms. We need to evaluate if this SDK will work with our app as-is and we'll get back to you after we do so.
