### ISSUE TITLE
"LOAD NEW RESOURCES" button won't work for the second time

### ISSUE THREAD

**Issue by BillHoo** [crowdin/mobile-sdk-android#57]
**Describe the bug**

A Distribution Hash could only work once, when i click the "LOAD NEW RESOURCES" button for the second time (i did click the Release button on the Crowdin side), it won't update my strings any more.

**To Reproduce**

1. Compile and install Android Examples with correct Distribution Hash.
1. Upload `strings.xml` from the example project to Crowdin, and translate some of the strings.
1. Add a new dist-hash to Crowdin page and click `Release` button.
1. Open the Example App, it shows the original texts.
1. Click `LOAD NEW RESOURCES` button, and translations made in step 2 is shown, work like a charm!
1. Get back to Crowdin page, translate more strings, make sure they are approved, and go to Distribution to click `Release` button again
1. Get back to example App, click `LOAD NEW RESOURCES` again, but new translations are not shown, and when debugging, the strings are empty `{"arrays":{},"language":"zh-CN","plurals":{},"strings":{}}`

**Expected behavior**
Once i released new strings from Crowdin page, and clicked the `LOAD` button, the example App should show the latest strings.

**Additional context**
Interest thing is, keep all the things not changed, and just add another New Distribution Hash, then Release it, and recompile the example App with the new hash, the latest strings will show. But this is not the solution, I want to just use one hash for one App, i don't want to re-compile my App.

**Comment by andrii-bodnar** [comment]
Hi @BillHoo!

We have explored this issue and convinced that it's related to the CDN cache.

CDN caches all the translation in release for up to 15 minutes and even when new translations are released, CDN may return it with a delay.

**Comment by BillHoo** [comment]
Thanks, it seems not a bug though, if there's a delay which can not avoid, maybe could update Crowdin's doc to point it out. The first time after read your doc, i really think the distribution is a WYSIWYG feature thus makes me think its a bug. anyway, thank you for explaining.
