### ISSUE TITLE
Unable to authorize through Google: disallowed_useragent (403)

### ISSUE THREAD

**Issue by TwoEightNine** [crowdin/mobile-sdk-android#78]
**Describe the bug**
When you try to log in using Google on auth page, Google says '403: disallowed_useragent'

**To Reproduce**
1. Implement crowdin SDK with screenshot and real-time update features enabled
2. Open your app
3. When crowdin suggests you to sign in, click 'OK'
4. On Crowdin auth page click 'Google'

**Expected behavior**
I expect to have an ability to continue logging in using Google

**Screenshots**
![image](https://user-images.githubusercontent.com/11145602/99933455-8f62b880-2d74-11eb-9c7a-bd7aed9b2fcc.png)

**Smartphones:**
Reproducible on several devices:
 - Xiaomi Mi A3 (Android 10)
 - Huawei P20 Lite (Android 8.0)

**Comment by TwoEightNine** [comment]
@andrii-bodnar i have found a solution and tried to create a fix, but it seems i dont have enough permissions to create pull request

i fixed it like that:
```
object UserAgentUtils {

    private const val VERSION_MOZILLA = "5.0"
    private const val VERSION_APPLE_KIT_SAFARI = "537.36"
    private const val VERSION_CHROME = "74.0.3729.157"

    fun getUserAgent(): String {
        val androidVersion = Build.VERSION.RELEASE
        val deviceName = "${Build.MANUFACTURER} ${Build.MODEL}"
        return "Mozilla/$VERSION_MOZILLA (Linux; Android $androidVersion; $deviceName) " +
                "AppleWebKit/$VERSION_APPLE_KIT_SAFARI (KHTML, like Gecko) " +
                "Chrome/$VERSION_CHROME " +
                "Mobile Safari/$VERSION_APPLE_KIT_SAFARI"
    }
}
```

and then in AuthActivity:
```
webView.settings.userAgentString = UserAgentUtils.getUserAgent()
```

**Comment by andrii-bodnar** [comment]
Hi @TwoEightNine,

Great, thank you so much for your involvement! :+1: 

You can fork this repo, make changes in the forked copy, and then you will be able to create a Pull Request to the current repository.
