### ISSUE TITLE
No translations for regional variation of language

### ISSUE THREAD

**Issue by TwoEightNine** [crowdin/mobile-sdk-android#81]
I'm trying to implement Crowdin SDK and I found out that regional variation of language is ignored.

**Case 1: device is using French french (`fr_FR`)**
Everything is going OK. I see correct translations in my app.

**Case 2.1: device is using Canadian french (`fr_CA`)**
I expect to see correct french translation, but actually translations are ignored, SDK uses default string.

**Case 2.2: device is using Canadian french (`fr_CA`) but trying to remove locale country**
I tried to fix this issue like this
`Locale.setDefault(Locale(Locale.getDefault().language))`
The same as in case 2.1.

In Crowdin admin panel only default french is used:
![image](https://user-images.githubusercontent.com/11145602/100072201-623a0700-2e55-11eb-9698-88995bea120e.png)

By the way, the SDK has mentioned limitations:
>Currently, Custom Languages, Dialects, and Language Mapping are not supported for Android SDK

**So my questions:** are these cases currently not supported as mentioned above? if it is supported, what should i do to fix it?

**Comment by andrii-bodnar** [comment]
Hi @TwoEightNine!

Try to add each dialect as a target language in your Crowdin project and translate some strings to check them in your app. Also, you will need to release the distribution in order to deliver translations to the CDN.

**Comment by TwoEightNine** [comment]
Thank you for your quick reply, @andrii-bodnar!

I cannot add dialects now due to corporative limitations but I'll try your suggestion and reply here.

Now I found out a workaround:
```
private val supportedLocales = mapOf(
        "fr" to Locale.FRANCE // etc
)
val currentLanguageCode = Locale.getDefault().language
supportedLocales[currentLanguageCode]
        ?.also(Locale::setDefault)
``` 

This will override regional locale with specified, translations will appear as needed! (`'fr-*' -> 'fr-FR'`)
