### ISSUE TITLE
Unable to sign in via Google: nothing happens after entering e-mail

### ISSUE THREAD

**Issue by TwoEightNine** [crowdin/mobile-sdk-android#82]
**Describe the bug**
On Google Sign In page when I enter e-mail and click 'Next', e-mail disappears (sometimes partially) and nothing more happens.

**To Reproduce**
1. Implement crowdin SDK with real-time update features enabled
2. Open your app
3. When crowdin suggests you to sign in, click 'OK'
4. On Crowdin auth page click 'Google'
5. On Google Sign In page enter e-mail and click 'Next'

**Expected behavior**
Google consumes my e-mail and prompts to enter my password

**Smartphone:**
 - Xiaomi Mi A3 (Android 10)
 - Android Studio Emulator (Android 10) 
 - Huawei P20 Lite (Android 8.0)

Crowdin SDK v1.2.1

**Comment by Natalia936** [comment]
Thank you, our team will take a look in the shortest terms
